#---------------
# Windows Builds
#---------------
.job_template: &build-windows
  stage: build
  script:
    - set TARGET_PLATFORM=%CI_JOB_NAME%
    - set TOOLCHAIN=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake
    - rd /s /q "%CI_PROJECT_DIR%/build/%TARGET_PLATFORM%"
    - mkdir "%CI_PROJECT_DIR%/build/%TARGET_PLATFORM%"
    - cd "%CI_PROJECT_DIR%/build/%TARGET_PLATFORM%"
    - cmake "%CI_PROJECT_DIR%" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DCMAKE_TOOLCHAIN_FILE=%TOOLCHAIN% -DVCPKG_TARGET_TRIPLET=%TRIPLET% -DCMAKE_GENERATOR_PLATFORM=%ARCH%
    - cmake --build . --target INSTALL --config %BUILD_TYPE%
  cache:
    untracked: true
    policy: push
  artifacts:
    untracked: true
    expire_in: 1 week

build-x64-windows-release:
  <<: *build-windows
  tags:
    - windows
    - release
  before_script:
    - set ARCH=x64
    - set BUILD_TYPE=Release
    - set TRIPLET=x64-windows
  cache:
    key: build-x64-windows-release
    paths:
      - build/build-x64-windows-release/bin/
      - build/build-x64-windows-release/data/

build-x64-windows-debug:
  <<: *build-windows
  tags:
    - windows
    - debug
  before_script:
    - set ARCH=x64
    - set BUILD_TYPE=Debug
    - set TRIPLET=x64-windows
  cache:
    key: build-x64-windows-debug
    paths:
      - build/build-x64-windows-debug/bin/
      - build/build-x64-windows-debug/data/
#---------------
# Windows Tests
#---------------
.job_template: &test-windows
  tags:
    - windows
  stage: test
  cache:
    policy: pull

test-x64-windows-release:
  <<: *test-windows
  dependencies:
    - build-x64-windows-release
  before_script:
    - cd %VCPKG_ROOT%/installed/x64-windows/bin
  script:
    - "%CI_PROJECT_DIR%/build/build-x64-windows-release/bin/test_pdal_c"
  cache:
    key: build-x64-windows-release
    paths:
      - build/build-x64-windows-release/bin/

test-x64-windows-debug:
  <<: *test-windows
  dependencies:
    - build-x64-windows-debug
  before_script:
    - cd %VCPKG_ROOT%/installed/x64-windows/debug/bin
  script:
   - "%CI_PROJECT_DIR%/build/build-x64-windows-debug/bin/test_pdal_cd"
  cache:
    key: build-x64-windows-debug
    policy: pull
    paths:
      - build/build-x64-windows-debug/bin/

#--------------------------
# Linux Builds (via Docker)
#--------------------------
#
.job_template: &build-linux
  stage: build
  image: simverge/pdalc-build-deps
  script:
    - export TARGET_PLATFORM=$CI_JOB_NAME
    - echo "Building $CI_PROJECT_NAME ($CI_COMMIT_REF_NAME branch) for $TARGET_PLATFORM"
    - rm -rf "$CI_PROJECT_DIR/build/$TARGET_PLATFORM" 
    - mkdir -p "$CI_PROJECT_DIR/build/$TARGET_PLATFORM"
    - cd "$CI_PROJECT_DIR/build/$TARGET_PLATFORM"
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE "$CI_PROJECT_DIR"
    - make
    - make install
  variables:
    GIT_STRATEGY: clone
  cache:
    untracked: true
    key: "$CI_JOB_NAME"
    policy: push
    paths:
      - build/$CI_JOB_NAME/bin/
      - build/$CI_JOB_NAME/data/
  artifacts:
    untracked: true
    expire_in: 1 week

.build-x64-linux-release:
  <<: *build-linux
  tags:
    - linux
    - docker
    - release
  before_script:
    - export BUILD_TYPE=Release

.build-x64-linux-debug:
  <<: *build-linux
  tags:
    - linux
    - docker
    - debug
  before_script:
    - export BUILD_TYPE=Debug

