sudo: required

language: minimal
services: docker

before_install:
  - docker pull simverge/pdalc-build-deps:alpine

#env:
#  - BUILD_TYPE=Release
#  - BUILD_TYPE=Debug

script:
  - dir $TRAVIS_BUILD_DIR
  - docker run -v $TRAVIS_BUILD_DIR:/pdalc -t simverge/pdalc-build-deps:alpine /pdalc/tests/travis/script.sh