sudo: required

# Required by SonarCloud - see https://docs.travis-ci.com/user/sonarcloud/
language: java
dist: trusty

services: docker

addons:
  sonarcloud:
    organization: "simverge"
    token:
      secure: $SONAR_TOKEN

env:
  - DISTRO=alpine BUILD_TYPE=Release
  - DISTRO=alpine BUILD_TYPE=Debug
  - DISTRO=ubuntu BUILD_TYPE=Release
  - DISTRO=ubuntu BUILD_TYPE=Debug

before_install:
  - docker pull simverge/pdalc-build-deps:$DISTRO

script:
  - chmod u+x $TRAVIS_BUILD_DIR/tests/travis/script.sh
  - docker run -e COVERITY_TOKEN -e TRAVIS_COMMIT -e TRAVIS_BRANCH -e BUILD_TYPE -e DISTRO -v $TRAVIS_BUILD_DIR:/pdalc -t simverge/pdalc-build-deps:$DISTRO /pdalc/tests/travis/script.sh
  - if [ "$DISTRO" = "alpine" ] && [ "$BUILD_TYPE" = "Release" ]; then sonar-scanner; fi
