sudo: required

language: minimal
services: docker

before_install:
  - docker pull simverge/pdalc-build-deps:alpine

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

script:
  - chmod u+x $TRAVIS_BUILD_DIR/tests/travis/script.sh
  - docker run -e TRAVIS_BRANCH -e BUILD_TYPE -v $TRAVIS_BUILD_DIR:/pdalc -t simverge/pdalc-build-deps:alpine /pdalc/tests/travis/script.sh