sudo: required

language: minimal
services: docker

before_install:
  - docker pull simverge/pdalc-build-deps:alpine

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

script:
  - docker run -v $TRAVIS_BUILD_DIR:/pdalc -t simverge/pdalc-build-deps:alpine -e "BRANCH=$TRAVIS_BRANCH" -e "BUILD_TYPE=$BUILD_TYPE" /pdalc/tests/travis/script.sh