name: Windows Build Test
on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout The PR
        uses: actions/checkout@v2
        
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v1.7.0
        
      - name: Install PDAL
        shell: pwsh
        run: conda install -c conda-forge pdal
        
      - name: Build
        shell: cmd
        run: |
          set TOOLCHAIN=""
          make
          
      - name: Test
        shell: cmd
        run: test_pdalc.exe

