name: Update Docs
on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout The PR
        uses: actions/checkout@v2
              
      - name: Build
        shell: bash
        run: |
          SOURCE=$(pwd)
          cd docs
          cat Doxyfile.in | \
          sed 's|${PROJECT_NAME}|pdal-c|' | \
          sed 's|${pdal-c_VERSION}|v2.0.0|' | \
          sed 's|${CMAKE_SOURCE_DIR}|$SOURCE|' \
          > Doxyfile

          cat Doxyfile

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.0
          


