name: Update Docs
on:
  release:
    types: [published]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout The Master
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 1
              
      - name: Build
        shell: bash
        run: |
          SOURCE=$(pwd)
          cd docs
          VERSION=$( basename ${GITHUB_REF} )
          echo "Version Being built: ${VERSION}"
          cat Doxyfile.in | \
          sed 's:${PROJECT_NAME}:pdal-c:' | \
          sed 's:${pdal-c_VERSION}: '$VERSION' :' | \
          sed 's:${CMAKE_SOURCE_DIR}:.:' | \
          sed 's:${PDAL_INCLUDE_DIRS}:NONE:' \
          > Doxyfile

      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.0
        with:
          doxyfile-path: 'docs/Doxyfile'

      - name: Commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Automatic Documentation Update" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      
          


