name: Update Docs
on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout The PR
        uses: actions/checkout@v2
        
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v1.7.0
        
      - name: Install PDAL
        shell: bash -l {0}
        run: conda install -c conda-forge pdal
        
      - name: Build
        shell: bash -l {0}
        run: |
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCONDA_BUILD=OFF .
          make
          make install
          
      - name: Test
        shell: bash -l {0}
        run: |
           ctest -VV

