name: Update Docs
on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout The PR
        uses: actions/checkout@v2
      
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.0
      
        
      - name: Build
        shell: bash -l {0}
        run: |
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCONDA_BUILD=OFF .
          make
          make install
          
      - name: Test
        shell: bash -l {0}
        run: |
           ctest -VV

