name: Windows Build Test
on:
  [pull-request]
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout The PR
        uses: actions/checkout@v2
        
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v1.7.0
        
      - name: Install PDAL
        shell: pwsh
        run: conda install -c conda-forge pdal
        
      - name: Build
        shell: cmd /C call {0}
        run: |
          set TOOLCHAIN=""
          make.bat
          
      - name: Test
        shell: cmd /C call {0}
        run: |
           cp build\x64-windows\source\pdal\release\pdalc.dll build\x64-windows\tests\pdal\release
           cd build\x64-windows\tests\pdal\release
           test_pdalc

